# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jay/deprince-group/plugins/mean_field_cqed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jay/deprince-group/plugins/mean_field_cqed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jay/deprince-group/plugins/mean_field_cqed/CMakeFiles /home/jay/deprince-group/plugins/mean_field_cqed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jay/deprince-group/plugins/mean_field_cqed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mean_field_cqed

# Build rule for target.
mean_field_cqed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mean_field_cqed
.PHONY : mean_field_cqed

# fast build rule for target.
mean_field_cqed/fast:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/build
.PHONY : mean_field_cqed/fast

frozen_natural_orbitals.o: frozen_natural_orbitals.cc.o

.PHONY : frozen_natural_orbitals.o

# target to build an object file
frozen_natural_orbitals.cc.o:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/frozen_natural_orbitals.cc.o
.PHONY : frozen_natural_orbitals.cc.o

frozen_natural_orbitals.i: frozen_natural_orbitals.cc.i

.PHONY : frozen_natural_orbitals.i

# target to preprocess a source file
frozen_natural_orbitals.cc.i:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/frozen_natural_orbitals.cc.i
.PHONY : frozen_natural_orbitals.cc.i

frozen_natural_orbitals.s: frozen_natural_orbitals.cc.s

.PHONY : frozen_natural_orbitals.s

# target to generate assembly for a file
frozen_natural_orbitals.cc.s:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/frozen_natural_orbitals.cc.s
.PHONY : frozen_natural_orbitals.cc.s

tdhf.o: tdhf.cc.o

.PHONY : tdhf.o

# target to build an object file
tdhf.cc.o:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/tdhf.cc.o
.PHONY : tdhf.cc.o

tdhf.i: tdhf.cc.i

.PHONY : tdhf.i

# target to preprocess a source file
tdhf.cc.i:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/tdhf.cc.i
.PHONY : tdhf.cc.i

tdhf.s: tdhf.cc.s

.PHONY : tdhf.s

# target to generate assembly for a file
tdhf.cc.s:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/tdhf.cc.s
.PHONY : tdhf.cc.s

tdhf_cqed.o: tdhf_cqed.cc.o

.PHONY : tdhf_cqed.o

# target to build an object file
tdhf_cqed.cc.o:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/tdhf_cqed.cc.o
.PHONY : tdhf_cqed.cc.o

tdhf_cqed.i: tdhf_cqed.cc.i

.PHONY : tdhf_cqed.i

# target to preprocess a source file
tdhf_cqed.cc.i:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/tdhf_cqed.cc.i
.PHONY : tdhf_cqed.cc.i

tdhf_cqed.s: tdhf_cqed.cc.s

.PHONY : tdhf_cqed.s

# target to generate assembly for a file
tdhf_cqed.cc.s:
	$(MAKE) -f CMakeFiles/mean_field_cqed.dir/build.make CMakeFiles/mean_field_cqed.dir/tdhf_cqed.cc.s
.PHONY : tdhf_cqed.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mean_field_cqed"
	@echo "... frozen_natural_orbitals.o"
	@echo "... frozen_natural_orbitals.i"
	@echo "... frozen_natural_orbitals.s"
	@echo "... tdhf.o"
	@echo "... tdhf.i"
	@echo "... tdhf.s"
	@echo "... tdhf_cqed.o"
	@echo "... tdhf_cqed.i"
	@echo "... tdhf_cqed.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

